export const en = {
  nav: {
    home: "Home",
    categories: "Categories",
    shops: "Shops",
    products: "Products",
    about: "About",
    contact: "Contact",
    login: "Login",
    register: "Register",
    logout: "Logout",
    profile: "Profile",
    dashboard: "Dashboard",
    admin: "Admin Panel",
    cart: "Cart",
    wishlist: "Wishlist",
    orders: "Orders",
    chat: "Chat",
    search: "Search",
    menu: "Menu",
  },
  hero: {
    title: "Buy & Sell Easily",
    subtitle: "Georgian online marketplace where all shops are in one space",
    cta: "Start Shopping",
    registerShop: "Open a Shop",
  },
  search: {
    placeholder: "Search products, shops...",
    filter: "Filter",
    noResults: "No results found",
  },
  categories: {
    title: "Categories",
    viewAll: "View All",
  },
  products: {
    title: "Products",
    newProducts: "New Products",
    popular: "Popular",
    featured: "Featured",
    bestOffers: "Best Offers",
    addToCart: "Add to Cart",
    addToWishlist: "Add to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    buyNow: "Buy Now",
    outOfStock: "Out of Stock",
    inStock: "In Stock",
    description: "Description",
    features: "Features",
    delivery: "Delivery",
    reviews: "Reviews",
    noProducts: "No products found",
    price: "Price",
    discount: "Discount",
    sortBy: "Sort By",
    filter: "Filter",
    category: "Category",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    rating: "Rating",
  },
  shop: {
    title: "Shops",
    popularShops: "Popular Shops",
    featured: "Featured Shops",
    visitShop: "Visit Shop",
    about: "About",
    contact: "Contact",
    products: "Products",
    noProducts: "No products",
    create: "Create Shop",
    edit: "Edit",
    settings: "Settings",
    name: "Shop Name",
    description: "Description",
    logo: "Logo",
    banner: "Banner",
  },
  auth: {
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    fullName: "Full Name",
    phone: "Phone",
    forgotPassword: "Forgot Password",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    registerLink: "Register",
    loginLink: "Login",
    success: "Login successful",
    error: "Login error",
    logout: "Logout",
    profile: "Profile",
    save: "Save",
    saved: "Saved",
  },
  cart: {
    title: "Cart",
    empty: "Cart is empty",
    total: "Total",
    subtotal: "Subtotal",
    shipping: "Shipping",
    discount: "Discount",
    checkout: "Checkout",
    continue: "Continue",
    remove: "Remove",
    quantity: "Quantity",
    coupon: "Coupon Code",
    applyCoupon: "Apply",
    orderSummary: "Order Summary",
    cardPayment: "Card Payment",
    cardNumber: "Card Number",
    cardholderName: "Cardholder Name",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    paypal: "PayPal",
    paypalRedirect: "Redirecting to PayPal...",
    paypalInfo: "Pay via PayPal secure system",
    cash: "Cash on Delivery",
    cashInfo: "Pay when you receive the order",
    payNow: "Pay Now",
    processingPayment: "Processing payment...",
    paymentSuccess: "Payment successful!",
    paymentFailed: "Payment failed",
    orderPlaced: "Order Placed!",
    orderNumber: "Order #",
    orderConfirmed: "Your order has been received and is being processed.",
    continueShopping: "Continue Shopping",
    viewOrder: "View Order",
    invalidCard: "Please enter valid card details",
  },
  wishlist: {
    title: "Wishlist",
    empty: "Wishlist is empty",
    addToCart: "Add to Cart",
    remove: "Remove",
  },
  orders: {
    title: "Orders",
    orderNumber: "Order #",
    date: "Date",
    status: "Status",
    total: "Total",
    view: "View",
    noOrders: "No orders",
    tracking: "Tracking",
    trackShipment: "Track Shipment",
    trackingNumber: "Tracking Number",
    orderDetails: "Order Details",
    items: "Items",
    shippingAddress: "Shipping Address",
    statuses: {
      NEW: "New",
      PROCESSING: "Processing",
      PACKED: "Packed",
      SHIPPED: "Shipped",
      IN_TRANSIT: "In Transit",
      DELIVERED: "Delivered",
      CANCELLED: "Cancelled",
    },
  },
  profile: {
    title: "Profile",
    personalInfo: "Personal Info",
    addresses: "Addresses",
    addAddress: "Add Address",
    editAddress: "Edit",
    deleteAddress: "Delete",
    defaultAddress: "Default Address",
    setDefault: "Set as Default",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone",
    street: "Street",
    city: "City",
    region: "Region",
    zipCode: "ZIP Code",
    save: "Save",
    saved: "Saved",
  },
  footer: {
    description: "Market - Georgian online marketplace where many shops are gathered in one space.",
    quickLinks: "Quick Links",
    forSellers: "For Sellers",
    forBuyers: "For Buyers",
    followUs: "Follow Us",
    rights: "All rights reserved",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    help: "Help",
    faq: "FAQ",
  },
  whyUs: {
    title: "Why Market?",
    secure: {
      title: "Secure Payment",
      desc: "Protected transactions with best technologies",
    },
    fast: {
      title: "Fast Delivery",
      desc: "Fast delivery throughout Georgia",
    },
    support: {
      title: "24/7 Support",
      desc: "Constant support anytime",
    },
    easy: {
      title: "Easy to Use",
      desc: "Simple interface for everyone",
    },
  },
  reviews: {
    title: "What Our Customers Say",
    write: "Write a Review",
    submit: "Submit",
    rating: "Rating",
    comment: "Comment",
    noReviews: "No reviews yet",
  },
  chat: {
    title: "Chat",
    placeholder: "Type a message...",
    send: "Send",
    noMessages: "No messages",
    startConversation: "Start Conversation",
    typeMessage: "Type a message...",
    online: "Online",
    offline: "Offline",
    attachFile: "Attach File",
    sendImage: "Send Image",
  },
  dashboard: {
    title: "Dashboard",
    overview: "Overview",
    products: "Products",
    orders: "Orders",
    analytics: "Analytics",
    settings: "Settings",
    todaySales: "Today's Sales",
    monthlySales: "Monthly Sales",
    revenue: "Revenue",
    totalOrders: "Orders",
    totalCustomers: "Customers",
    bestSellers: "Best Sellers",
    addProduct: "Add Product",
    editProduct: "Edit",
    deleteProduct: "Delete",
    subscription: "Subscription",
    currentPlan: "Current Plan",
    upgrade: "Upgrade",
    expired: "Expired",
    expiresAt: "Expires At",
    daysLeft: "Days Left",
  },
  subscription: {
    title: "Subscription Plans",
    free: "Free",
    basic: "Basic",
    standard: "Standard",
    premium: "Premium",
    current: "Current",
    subscribe: "Subscribe",
    features: "Features",
    productsLimit: "Products Limit",
    ordersLimit: "Orders Limit",
    support24h: "24/7 Support",
    analytics: "Analytics",
    chatSupport: "Chat Support",
    featuredTag: "Featured Tag",
    customDomain: "Custom Domain",
    price_month: "Month",
    price_year: "Year",
    monthly: "Monthly",
    yearly: "Yearly",
  },
  admin: {
    title: "Admin Panel",
    users: "Users",
    shops: "Shops",
    categories: "Categories",
    subscriptions: "Subscriptions",
    finance: "Finance",
    stats: "Stats",
    complaints: "Complaints",
    block: "Block",
    unblock: "Unblock",
    delete: "Delete",
    approve: "Approve",
    reject: "Reject",
  },
  common: {
    loading: "Loading...",
    error: "Error",
    success: "Success",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    view: "View",
    close: "Close",
    back: "Back",
    next: "Next",
    confirm: "Confirm",
    search: "Search",
    noData: "No data",
    yes: "Yes",
    no: "No",
    all: "All",
    free: "Free",
    currency: "₾",
    showMore: "Show More",
    showLess: "Show Less",
  },
};

export type EnKey = keyof typeof en;
