export const ge = {
  nav: {
    home: "მთავარი",
    categories: "კატეგორიები",
    shops: "მაღაზიები",
    products: "პროდუქტები",
    about: "ჩვენს შესახებ",
    contact: "კონტაქტი",
    login: "შესვლა",
    register: "რეგისტრაცია",
    logout: "გასვლა",
    profile: "პროფილი",
    dashboard: "დეშბორდი",
    admin: "ადმინ პანელი",
    cart: "კალათა",
    wishlist: "სურვილების სია",
    orders: "შეკვეთები",
    chat: "ჩატი",
    search: "ძებნა",
    menu: "მენიუ",
  },
  hero: {
    title: "იყიდე და გაყიდე მარტივად",
    subtitle: "ქართული ონლაინ მარკეტპლეისი, სადაც ყველა მაღაზია ერთ სივრცეშია",
    cta: "დაიწყე ყიდვა",
    registerShop: "გახსენი მაღაზია",
  },
  search: {
    placeholder: "მოძებნე პროდუქტები, მაღაზიები...",
    filter: "ფილტრი",
    noResults: "შედეგი ვერ მოიძებნა",
  },
  categories: {
    title: "კატეგორიები",
    viewAll: "ყველას ნახვა",
  },
  products: {
    title: "პროდუქტები",
    newProducts: "ახალი პროდუქტები",
    popular: "პოპულარული",
    featured: "რეკომენდებული",
    bestOffers: "საუკეთესო შეთავაზებები",
    addToCart: "კალათაში დამატება",
    addToWishlist: "სურვილებში დამატება",
    removeFromWishlist: "სურვილებიდან ამოღება",
    buyNow: "ყიდვა",
    outOfStock: "ამოწურულია",
    inStock: "მარაგშია",
    description: "აღწერა",
    features: "მახასიათებლები",
    delivery: "მიწოდება",
    reviews: "შეფასებები",
    noProducts: "პროდუქტები არ არის",
    price: "ფასი",
    discount: "ფასდაკლება",
    sortBy: "სორტირება",
    filter: "ფილტრი",
    category: "კატეგორია",
    minPrice: "მინ. ფასი",
    maxPrice: "მაქს. ფასი",
    rating: "რეიტინგი",
  },
  shop: {
    title: "მაღაზიები",
    popularShops: "პოპულარული მაღაზიები",
    featured: "რეკომენდებული მაღაზიები",
    visitShop: "მაღაზიის ნახვა",
    about: "ჩვენ შესახებ",
    contact: "კონტაქტი",
    products: "პროდუქტები",
    noProducts: "პროდუქტები არ არის",
    create: "მაღაზიის შექმნა",
    edit: "რედაქტირება",
    settings: "პარამეტრები",
    name: "მაღაზიის სახელი",
    description: "აღწერა",
    logo: "ლოგო",
    banner: "ბანერი",
  },
  auth: {
    login: "შესვლა",
    register: "რეგისტრაცია",
    email: "ელ. ფოსტა",
    password: "პაროლი",
    confirmPassword: "გაიმეორეთ პაროლი",
    fullName: "სრული სახელი",
    phone: "ტელეფონი",
    forgotPassword: "პაროლის დავიწყება",
    noAccount: "არ გაქვთ ანგარიში?",
    hasAccount: "უკვე გაქვთ ანგარიში?",
    registerLink: "დარეგისტრირდით",
    loginLink: "შედით სისტემაში",
    success: "წარმატებული ავტორიზაცია",
    error: "ავტორიზაციის შეცდომა",
    logout: "გასვლა",
    profile: "პროფილი",
    save: "შენახვა",
    saved: "შენახულია",
  },
  cart: {
    title: "კალათა",
    empty: "კალათა ცარიელია",
    total: "სულ",
    subtotal: "ქვეჯამი",
    shipping: "მიწოდება",
    discount: "ფასდაკლება",
    checkout: "გადახდა",
    continue: "ყიდვის გაგრძელება",
    remove: "წაშლა",
    quantity: "რაოდენობა",
    coupon: "კუპონი",
    applyCoupon: "გამოყენება",
    orderSummary: "შეკვეთის შეჯამება",
    cardPayment: "ბარათით გადახდა",
    cardNumber: "ბარათის ნომერი",
    cardholderName: "მფლობელის სახელი",
    expiryDate: "ვადის გასვლის თარიღი",
    cvv: "CVV",
    paypal: "PayPal",
    paypalRedirect: "PayPal-ზე გადამისამართება",
    paypalInfo: "გადახდა PayPal-ის უსაფრთხო სისტემით",
    cash: "ნაღდი ანგარიშსწორება",
    cashInfo: "გადაიხადეთ შეკვეთის მიღებისას",
    payNow: "გადახდა",
    processingPayment: "მიმდინარეობს გადახდა...",
    paymentSuccess: "გადახდა წარმატებით დასრულდა!",
    paymentFailed: "გადახდა ვერ მოხერხდა",
    orderPlaced: "შეკვეთა განთავსებულია!",
    orderNumber: "შეკვეთის ნომერი",
    orderConfirmed: "თქვენი შეკვეთა მიღებულია და დამუშავების პროცესშია.",
    continueShopping: "ყიდვის გაგრძელება",
    viewOrder: "შეკვეთის ნახვა",
    invalidCard: "გთხოვთ შეიყვანოთ ბარათის სწორი მონაცემები",
  },
  wishlist: {
    title: "სურვილების სია",
    empty: "სურვილების სია ცარიელია",
    addToCart: "კალათაში დამატება",
    remove: "წაშლა",
  },
  orders: {
    title: "შეკვეთები",
    orderNumber: "შეკვეთის #",
    date: "თარიღი",
    status: "სტატუსი",
    total: "თანხა",
    view: "ნახვა",
    noOrders: "შეკვეთები არ არის",
    tracking: "თრექინგი",
    trackShipment: "ამანათის თვალყურის დევნება",
    trackingNumber: "თრექინგ ნომერი",
    orderDetails: "შეკვეთის დეტალები",
    items: "პროდუქტები",
    shippingAddress: "მიწოდების მისამართი",
    statuses: {
      NEW: "ახალი",
      PROCESSING: "დამუშავებაში",
      PACKED: "შეფუთულია",
      SHIPPED: "გაგზავნილია",
      IN_TRANSIT: "გზაშია",
      DELIVERED: "მიტანილია",
      CANCELLED: "გაუქმებულია",
    },
  },
  profile: {
    title: "პროფილი",
    personalInfo: "პირადი ინფორმაცია",
    addresses: "მისამართები",
    addAddress: "მისამართის დამატება",
    editAddress: "რედაქტირება",
    deleteAddress: "წაშლა",
    defaultAddress: "მთავარი მისამართი",
    setDefault: "მთავარად დაყენება",
    fullName: "სრული სახელი",
    email: "ელ. ფოსტა",
    phone: "ტელეფონი",
    street: "ქუჩა",
    city: "ქალაქი",
    region: "რეგიონი",
    zipCode: "ინდექსი",
    save: "შენახვა",
    saved: "შენახულია",
  },
  footer: {
    description: "მარკეტი - ქართული ონლაინ მარკეტპლეისი, სადაც მრავალი მაღაზია ერთ სივრცეშია თავმოყრილი.",
    quickLinks: "სწრაფი ლინკები",
    forSellers: "გამყიდველებს",
    forBuyers: "მყიდველებს",
    followUs: "გამოგვყევით",
    rights: "ყველა უფლება დაცულია",
    terms: "წესები და პირობები",
    privacy: "კონფიდენციალურობა",
    help: "დახმარება",
    faq: "ხშირი კითხვები",
  },
  whyUs: {
    title: "რატომ მარკეტი?",
    secure: {
      title: "უსაფრთხო გადახდა",
      desc: "დაცული ტრანზაქციები საუკეთესო ტექნოლოგიებით",
    },
    fast: {
      title: "სწრაფი მიწოდება",
      desc: "მთელი საქართველოს მასშტაბით სწრაფი მიწოდება",
    },
    support: {
      title: "მხარდაჭერა 24/7",
      desc: "მუდმივი მხარდაჭერა ნებისმიერ დროს",
    },
    easy: {
      title: "მარტივი გამოყენება",
      desc: "მარტივი ინტერფეისი ყველასთვის გასაგები",
    },
  },
  reviews: {
    title: "რას ამბობენ ჩვენი მომხმარებლები",
    write: "დაწერე შეფასება",
    submit: "გაგზავნა",
    rating: "რეიტინგი",
    comment: "კომენტარი",
    noReviews: "შეფასებები არ არის",
  },
  chat: {
    title: "ჩატი",
    placeholder: "დაწერეთ მესიჯი...",
    send: "გაგზავნა",
    noMessages: "მესიჯები არ არის",
    startConversation: "დაიწყეთ საუბარი",
    typeMessage: "დაწერეთ მესიჯი...",
    online: "აქტიური",
    offline: "არააქტიური",
    attachFile: "ფაილის დამატება",
    sendImage: "სურათის გაგზავნა",
  },
  dashboard: {
    title: "დეშბორდი",
    overview: "მიმოხილვა",
    products: "პროდუქტები",
    orders: "შეკვეთები",
    analytics: "ანალიტიკა",
    settings: "პარამეტრები",
    todaySales: "დღევანდელი გაყიდვები",
    monthlySales: "თვიური გაყიდვები",
    revenue: "შემოსავალი",
    totalOrders: "შეკვეთები",
    totalCustomers: "მომხმარებლები",
    bestSellers: "ყველაზე გაყიდვადი",
    addProduct: "პროდუქტის დამატება",
    editProduct: "რედაქტირება",
    deleteProduct: "წაშლა",
    subscription: "აბონიმენტი",
    currentPlan: "მიმდინარე გეგმა",
    upgrade: "განახლება",
    expired: "ვადა გაუვიდა",
    expiresAt: "ვადა იწურება",
    daysLeft: "დარჩენილი დღე",
  },
  subscription: {
    title: "აბონიმენტის გეგმები",
    free: "უფასო",
    basic: "ბეისიკი",
    standard: "სტანდარტი",
    premium: "პრემიუმი",
    current: "მიმდინარე",
    subscribe: "გამოწერა",
    features: "შესაძლებლობები",
    productsLimit: "პროდუქტების ლიმიტი",
    ordersLimit: "შეკვეთების ლიმიტი",
    support24h: "24/7 მხარდაჭერა",
    analytics: "ანალიტიკა",
    chatSupport: "ჩატის მხარდაჭერა",
    featuredTag: "გამორჩეული ტეგი",
    customDomain: "საკუთარი დომენი",
    price_month: "თვე",
    price_year: "წელი",
    monthly: "თვიური",
    yearly: "წლიური",
  },
  admin: {
    title: "ადმინ პანელი",
    users: "მომხმარებლები",
    shops: "მაღაზიები",
    categories: "კატეგორიები",
    subscriptions: "აბონიმენტები",
    finance: "ფინანსები",
    stats: "სტატისტიკა",
    complaints: "საჩივრები",
    block: "დაბლოკვა",
    unblock: "განბლოკვა",
    delete: "წაშლა",
    approve: "დამტკიცება",
    reject: "უარყოფა",
  },
  common: {
    loading: "იტვირთება...",
    error: "შეცდომა",
    success: "წარმატება",
    save: "შენახვა",
    cancel: "გაუქმება",
    delete: "წაშლა",
    edit: "რედაქტირება",
    create: "შექმნა",
    view: "ნახვა",
    close: "დახურვა",
    back: "უკან",
    next: "შემდეგი",
    confirm: "დადასტურება",
    search: "ძებნა",
    noData: "მონაცემები არ არის",
    yes: "კი",
    no: "არა",
    all: "ყველა",
    free: "უფასო",
    currency: "₾",
    showMore: "მეტის ნახვა",
    showLess: "ნაკლების ნახვა",
  },

};

export type GeKey = keyof typeof ge;
