export const ru = {
  nav: {
    home: "Главная",
    categories: "Категории",
    shops: "Магазины",
    products: "Товары",
    about: "О нас",
    contact: "Контакты",
    login: "Вход",
    register: "Регистрация",
    logout: "Выход",
    profile: "Профиль",
    dashboard: "Панель",
    admin: "Админ панель",
    cart: "Корзина",
    wishlist: "Избранное",
    orders: "Заказы",
    chat: "Чат",
    search: "Поиск",
    menu: "Меню",
  },
  hero: {
    title: "Покупай и Продавай Легко",
    subtitle: "Грузинский онлайн маркетплейс, где все магазины в одном месте",
    cta: "Начать покупки",
    registerShop: "Открыть магазин",
  },
  search: {
    placeholder: "Поиск товаров, магазинов...",
    filter: "Фильтр",
    noResults: "Ничего не найдено",
  },
  categories: {
    title: "Категории",
    viewAll: "Все",
  },
  products: {
    title: "Товары",
    newProducts: "Новые товары",
    popular: "Популярные",
    featured: "Рекомендуемые",
    bestOffers: "Лучшие предложения",
    addToCart: "В корзину",
    addToWishlist: "В избранное",
    removeFromWishlist: "Из избранного",
    buyNow: "Купить",
    outOfStock: "Нет в наличии",
    inStock: "В наличии",
    description: "Описание",
    features: "Характеристики",
    delivery: "Доставка",
    reviews: "Отзывы",
    noProducts: "Товары не найдены",
    price: "Цена",
    discount: "Скидка",
    sortBy: "Сортировка",
    filter: "Фильтр",
    category: "Категория",
    minPrice: "Мин. цена",
    maxPrice: "Макс. цена",
    rating: "Рейтинг",
  },
  shop: {
    title: "Магазины",
    popularShops: "Популярные магазины",
    featured: "Рекомендуемые магазины",
    visitShop: "Посетить",
    about: "О нас",
    contact: "Контакты",
    products: "Товары",
    noProducts: "Товаров нет",
    create: "Создать магазин",
    edit: "Редактировать",
    settings: "Настройки",
    name: "Название",
    description: "Описание",
    logo: "Логотип",
    banner: "Баннер",
  },
  auth: {
    login: "Вход",
    register: "Регистрация",
    email: "Эл. почта",
    password: "Пароль",
    confirmPassword: "Подтвердите пароль",
    fullName: "Полное имя",
    phone: "Телефон",
    forgotPassword: "Забыли пароль",
    noAccount: "Нет аккаунта?",
    hasAccount: "Уже есть аккаунт?",
    registerLink: "Зарегистрироваться",
    loginLink: "Войти",
    success: "Успешный вход",
    error: "Ошибка входа",
    logout: "Выход",
    profile: "Профиль",
    save: "Сохранить",
    saved: "Сохранено",
  },
  cart: {
    title: "Корзина",
    empty: "Корзина пуста",
    total: "Итого",
    subtotal: "Подытог",
    shipping: "Доставка",
    discount: "Скидка",
    checkout: "Оплата",
    continue: "Продолжить",
    remove: "Удалить",
    quantity: "Количество",
    coupon: "Купон",
    applyCoupon: "Применить",
    orderSummary: "Итого заказа",
    cardPayment: "Оплата картой",
    cardNumber: "Номер карты",
    cardholderName: "Владелец карты",
    expiryDate: "Срок действия",
    cvv: "CVV",
    paypal: "PayPal",
    paypalRedirect: "Перенаправление на PayPal...",
    paypalInfo: "Оплата через безопасную систему PayPal",
    cash: "Наличные",
    cashInfo: "Оплата при получении",
    payNow: "Оплатить",
    processingPayment: "Обработка платежа...",
    paymentSuccess: "Оплата прошла успешно!",
    paymentFailed: "Оплата не удалась",
    orderPlaced: "Заказ оформлен!",
    orderNumber: "Заказ №",
    orderConfirmed: "Ваш заказ принят и обрабатывается.",
    continueShopping: "Продолжить",
    viewOrder: "Заказ",
    invalidCard: "Введите правильные данные карты",
  },
  wishlist: {
    title: "Избранное",
    empty: "Избранное пусто",
    addToCart: "В корзину",
    remove: "Удалить",
  },
  orders: {
    title: "Заказы",
    orderNumber: "Заказ №",
    date: "Дата",
    status: "Статус",
    total: "Сумма",
    view: "Просмотр",
    noOrders: "Заказов нет",
    tracking: "Отслеживание",
    trackShipment: "Отследить",
    trackingNumber: "Номер отслеживания",
    orderDetails: "Детали заказа",
    items: "Товары",
    shippingAddress: "Адрес доставки",
    statuses: {
      NEW: "Новый",
      PROCESSING: "Обрабатывается",
      PACKED: "Упакован",
      SHIPPED: "Отправлен",
      IN_TRANSIT: "В пути",
      DELIVERED: "Доставлен",
      CANCELLED: "Отменён",
    },
  },
  profile: {
    title: "Профиль",
    personalInfo: "Личная информация",
    addresses: "Адреса",
    addAddress: "Добавить адрес",
    editAddress: "Изменить",
    deleteAddress: "Удалить",
    defaultAddress: "Основной адрес",
    setDefault: "По умолчанию",
    fullName: "Полное имя",
    email: "Эл. почта",
    phone: "Телефон",
    street: "Улица",
    city: "Город",
    region: "Регион",
    zipCode: "Индекс",
    save: "Сохранить",
    saved: "Сохранено",
  },
  footer: {
    description: "Маркет - Грузинский онлайн маркетплейс, где много магазинов в одном месте.",
    quickLinks: "Быстрые ссылки",
    forSellers: "Продавцам",
    forBuyers: "Покупателям",
    followUs: "Мы в соцсетях",
    rights: "Все права защищены",
    terms: "Условия",
    privacy: "Конфиденциальность",
    help: "Помощь",
    faq: "Вопросы",
  },
  whyUs: {
    title: "Почему Маркет?",
    secure: {
      title: "Безопасная оплата",
      desc: "Защищенные транзакции",
    },
    fast: {
      title: "Быстрая доставка",
      desc: "Быстрая доставка по всей Грузии",
    },
    support: {
      title: "Поддержка 24/7",
      desc: "Постоянная поддержка",
    },
    easy: {
      title: "Простота",
      desc: "Простой интерфейс для всех",
    },
  },
  reviews: {
    title: "Отзывы клиентов",
    write: "Написать отзыв",
    submit: "Отправить",
    rating: "Оценка",
    comment: "Комментарий",
    noReviews: "Отзывов пока нет",
  },
  chat: {
    title: "Чат",
    placeholder: "Напишите сообщение...",
    send: "Отправить",
    noMessages: "Нет сообщений",
    startConversation: "Начать чат",
    typeMessage: "Напишите сообщение...",
    online: "Онлайн",
    offline: "Офлайн",
    attachFile: "Прикрепить файл",
    sendImage: "Отправить изображение",
  },
  dashboard: {
    title: "Панель",
    overview: "Обзор",
    products: "Товары",
    orders: "Заказы",
    analytics: "Аналитика",
    settings: "Настройки",
    todaySales: "Продажи сегодня",
    monthlySales: "Продажи за месяц",
    revenue: "Доход",
    totalOrders: "Заказы",
    totalCustomers: "Клиенты",
    bestSellers: "Хиты продаж",
    addProduct: "Добавить товар",
    editProduct: "Изменить",
    deleteProduct: "Удалить",
    subscription: "Подписка",
    currentPlan: "Текущий план",
    upgrade: "Улучшить",
    expired: "Истёк",
    expiresAt: "Истекает",
    daysLeft: "Осталось дней",
  },
  subscription: {
    title: "Планы подписки",
    free: "Бесплатный",
    basic: "Базовый",
    standard: "Стандартный",
    premium: "Премиум",
    current: "Текущий",
    subscribe: "Подписаться",
    features: "Возможности",
    productsLimit: "Лимит товаров",
    ordersLimit: "Лимит заказов",
    support24h: "24/7 Поддержка",
    analytics: "Аналитика",
    chatSupport: "Чат поддержка",
    featuredTag: "Рекомендуемый тег",
    customDomain: "Свой домен",
    price_month: "Месяц",
    price_year: "Год",
    monthly: "Ежемесячно",
    yearly: "Ежегодно",
  },
  admin: {
    title: "Админ панель",
    users: "Пользователи",
    shops: "Магазины",
    categories: "Категории",
    subscriptions: "Подписки",
    finance: "Финансы",
    stats: "Статистика",
    complaints: "Жалобы",
    block: "Заблокировать",
    unblock: "Разблокировать",
    delete: "Удалить",
    approve: "Одобрить",
    reject: "Отклонить",
  },
  common: {
    loading: "Загрузка...",
    error: "Ошибка",
    success: "Успешно",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Изменить",
    create: "Создать",
    view: "Просмотр",
    close: "Закрыть",
    back: "Назад",
    next: "Далее",
    confirm: "Подтвердить",
    search: "Поиск",
    noData: "Нет данных",
    yes: "Да",
    no: "Нет",
    all: "Все",
    free: "Бесплатно",
    currency: "₾",
    showMore: "Показать ещё",
    showLess: "Скрыть",
  },
};

export type RuKey = keyof typeof ru;
